# Generated by Django 3.2.4 on 2021-07-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller_api', '0001_initial'),
        ('blogs', '0002_alter_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='bookmark_users',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_blogs', to='traveller_api.Traveller'),
        ),
    ]
