# Generated by Django 3.2.4 on 2021-07-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller_api', '0001_initial'),
        ('blogs', '0003_alter_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='disliked_users',
            field=models.ManyToManyField(blank=True, related_name='dislikedcomments', to='traveller_api.Traveller'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='likedcomments', to='traveller_api.Traveller'),
        ),
    ]
