# Generated by Django 3.2.4 on 2021-08-09 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20210809_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='public_post',
            new_name='public_blog',
        ),
    ]
