# Generated by Django 3.2.4 on 2021-08-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_notification_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='public_post',
            field=models.BooleanField(default=True),
        ),
    ]
