# Generated by Django 3.2.4 on 2021-08-09 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places_api', '0002_place_keywords'),
        ('traveller_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='post/%Y/%m/%d/')),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('public_post', models.BooleanField(default=True)),
                ('bookmark_users', models.ManyToManyField(blank=True, related_name='bookmarked_posts', to='traveller_api.Traveller')),
                ('like_users', models.ManyToManyField(blank=True, related_name='likedposts', to='traveller_api.Traveller')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='places_api.place')),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='traveller_api.traveller')),
            ],
        ),
        migrations.CreateModel(
            name='Post_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(blank=True, default=False)),
                ('is_comment', models.BooleanField(blank=True, default=False)),
                ('comment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.comment')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='traveller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='traveller_api.traveller'),
        ),
    ]
