# Generated by Django 3.2.4 on 2021-07-22 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traveller_api', '0001_initial'),
        ('places_api', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='post/%Y/%m/%d/')),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('public_post', models.BooleanField(default=True)),
                ('like_users', models.ManyToManyField(blank=True, related_name='likedposts', to='traveller_api.Traveller')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='places_api.place')),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='traveller_api.traveller')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.post')),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='traveller_api.traveller')),
            ],
        ),
    ]
