# Generated by Django 3.2.4 on 2021-07-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller_api', '0001_initial'),
        ('post', '0003_alter_post_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookmark_users',
            field=models.ManyToManyField(blank=True, related_name='bookmarks_post', to='traveller_api.Traveller'),
        ),
    ]
