# Generated by Django 3.2.4 on 2021-08-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='keywords',
            field=models.TextField(blank=True),
        ),
    ]
