# Generated by Django 3.2.4 on 2021-08-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_api', '0002_place_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
