# Generated by Django 3.2.4 on 2021-08-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_api', '0004_auto_20210809_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
