# Generated by Django 3.2.4 on 2021-07-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveller_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveller',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='traveller',
            name='following',
        ),
    ]
