# Generated by Django 3.2.4 on 2021-08-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'other')], max_length=10),
        ),
    ]
