# Generated by Django 3.2.4 on 2021-07-20 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveller_api', '0002_auto_20210720_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravellerFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_traveller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='traveller_api.traveller')),
                ('traveller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='traveller_api.traveller')),
            ],
            options={
                'unique_together': {('traveller_id', 'following_traveller_id')},
            },
        ),
    ]
