# Generated by Django 3.2.4 on 2021-07-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller_api', '0002_auto_20210719_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveller',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_traveller_api_traveller_followers_+', to='traveller_api.Traveller'),
        ),
        migrations.AddField(
            model_name='traveller',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_traveller_api_traveller_following_+', to='traveller_api.Traveller'),
        ),
    ]
