# Generated by Django 3.2.4 on 2021-08-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller_api', '0002_alter_traveller_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='photo_main',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_photos/%Y/%m/%d/'),
        ),
    ]
