# Generated by Django 3.2.4 on 2021-07-19 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveller_api', '0003_auto_20210719_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveller',
            name='followers',
        ),
    ]
