# Generated by Django 3.2.4 on 2021-07-19 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveller_api', '0004_remove_traveller_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveller',
            name='following',
        ),
        migrations.CreateModel(
            name='TravellerFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='traveller_api.traveller')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='traveller_api.traveller')),
            ],
        ),
    ]
