# Generated by Django 3.2.4 on 2021-07-19 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveller_api', '0005_auto_20210719_0629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travellerfollowing',
            old_name='following_user_id',
            new_name='following_traveller_id',
        ),
        migrations.RenameField(
            model_name='travellerfollowing',
            old_name='user_id',
            new_name='traveller_id',
        ),
    ]
