# Generated by Django 3.2.4 on 2021-07-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveller_api', '0006_auto_20210719_0647'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='travellerfollowing',
            unique_together={('traveller_id', 'following_traveller_id')},
        ),
    ]
