# Generated by Django 3.2.4 on 2021-08-09 02:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('email_verification', models.BooleanField(default=True)),
                ('password_reset', models.BooleanField(default=False)),
                ('allow_reset', models.BooleanField(default=False)),
                ('verified_email', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 8, 9, 2, 41, 33, 91582, tzinfo=utc))),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
