# Generated by Django 3.2.4 on 2021-07-25 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 25, 21, 5, 56, 546782)),
        ),
    ]
