# Generated by Django 3.2.4 on 2021-07-25 17:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0003_alter_otp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='allow_reset',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 25, 17, 11, 40, 488285, tzinfo=utc)),
        ),
    ]
