# Generated by Django 3.2.4 on 2021-07-25 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0004_auto_20210725_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='verified_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 25, 18, 2, 13, 151071, tzinfo=utc)),
        ),
    ]
