# Generated by Django 3.2.4 on 2021-07-25 18:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0006_auto_20210726_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 25, 18, 37, 21, 556020, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='email_verification',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='password_reset',
            field=models.BooleanField(default=False),
        ),
    ]
