# Generated by Django 3.2.4 on 2021-08-09 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0001_initial'),
        ('traveller_api', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CHAT', 'chat'), ('POST', 'post'), ('BLOG', 'blog'), ('FOLLOW', 'follow')], max_length=7)),
                ('blog_noti', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.blog_notification')),
                ('post_noti', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post_notification')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('is_new', models.BooleanField(default=True)),
                ('is_read', models.BooleanField(default=False)),
                ('noti_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='notification.notification_type')),
                ('receipent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_notifications', to='traveller_api.traveller')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='traveller_api.traveller')),
            ],
        ),
    ]
