# Generated by Django 3.2.4 on 2021-08-09 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0001_initial'),
        ('traveller_api', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_type',
            name='post_noti',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post_notification'),
        ),
        migrations.AddField(
            model_name='notification',
            name='noti_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='notification.notification_type'),
        ),
        migrations.AddField(
            model_name='notification',
            name='receipent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_notifications', to='traveller_api.traveller'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='traveller_api.traveller'),
        ),
    ]
