# Generated by Django 3.2.4 on 2021-08-06 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_notification'),
        ('blogs', '0005_alter_blog_notification_comment_id'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='noti_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='notification.notification_type'),
        ),
        migrations.AlterField(
            model_name='notification_type',
            name='Blog_Noti',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.blog_notification'),
        ),
        migrations.AlterField(
            model_name='notification_type',
            name='Post_Noti',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post_notification'),
        ),
    ]
