# Generated by Django 3.2.4 on 2021-08-06 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_notification_comment_id'),
        ('post', '0006_post_notification'),
        ('notification', '0002_auto_20210806_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_type',
            name='Blog_Noti',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.blog_notification'),
        ),
        migrations.AlterField(
            model_name='notification_type',
            name='Post_Noti',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post_notification'),
        ),
    ]
