# Generated by Django 3.2.4 on 2021-08-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_type',
            name='category',
            field=models.CharField(choices=[('POST', 'post'), ('BLOG', 'blog'), ('FOLLOW', 'follow')], max_length=7),
        ),
    ]
