# Generated by Django 3.2.4 on 2021-08-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20210806_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification_type',
            old_name='Blog_Noti',
            new_name='blog_noti',
        ),
        migrations.RenameField(
            model_name='notification_type',
            old_name='Post_Noti',
            new_name='post_noti',
        ),
    ]
