# Generated by Django 3.2.4 on 2021-08-10 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_type_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='noti_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='notification.notification_type'),
        ),
    ]
