# Generated by Django 3.2.4 on 2021-08-10 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_place'),
        ('blogs', '0004_rename_public_post_blog_public_blog'),
        ('notification', '0005_auto_20210810_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_type',
            name='blog_noti',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.blog_notification'),
        ),
        migrations.AlterField(
            model_name='notification_type',
            name='post_noti',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post_notification'),
        ),
    ]
